service: app-demo-revstar

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-iam-roles-per-function

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: dev
  region: 'us-east-1'
  environment:
    COMPANIES_TABLE_NAME: ${self:custom.CompaniesTable.name}
    ARTICLES_TABLE_NAME: ${self:custom.ArticlesTable.name}
  iamRoleStatements:
    - ${file(resources/iam/CompaniesTable.yml):CompaniesTable}
    - ${file(resources/iam/ArticlesTable.yml):ArticlesTable}
    - ${file(resources/iam/SES.yml):SES}
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  - ${file(resources/functions/CompaniesAPI.yml)}
  - ${file(resources/functions/ArticlesAPI.yml)}
  - ${file(resources/functions/PdfAPI.yml)}

resources:
  - ${file(resources/database/Model.yml)}

custom:
  CompaniesTable:
    name: !Ref CompaniesTable
    arn: !GetAtt CompaniesTable.Arn
  ArticlesTable:
    name: !Ref ArticlesTable
    arn: !GetAtt ArticlesTable.Arn
  esbuild:
    external:
      - pdfkit
